USE HEMANT;

###### SHOWS ALL COLUMNS AND ROWS OF TABLE #########

SELECT * FROM SALARIES;

### SHOW ONLY EMPLOYEENAME AND JOBTITLE COLUMN
SELECT EMPLOYEENAME , JOBTITLE FROM SALARIES;

########## SHOWS THE NUMBERS OF EMPLOYEES IN THE TABLE #########

SELECT * FROM SALARIES;

SELECT COUNT(*) AS EMP FROM SALARIES;

#### SHOWS THE UNIQUE JOB TITLE IN TABLE ########

SELECT DISTINCT(JOBTITLE) FROM SALARIES;

###### SHOW THE JOB TITLE AND OVERTIMEPAY FOR EMPLOYEES WITH OVERTIMEPAY GRATER THAN 50000 #########

SELECT JOBTITLE, OVERTIMEPAY FROM SALARIES
WHERE OVERTIMEPAY > 50000;

######### SHOW AVERAGE BASEPAY FOR ALL EMPLOYEES ############

SELECT * FROM SALARIES;

SELECT EMPLOYEENAME, JOBTITLE, AVG(BASEPAY) AS AVGBASEPAY FROM SALARIES
GROUP BY JOBTITLE,EMPLOYEENAME
ORDER BY AVGBASEPAY DESC;

###### SHOW THE TOP 10 HIGHEST PAID EMPLOYEES #######

SELECT * FROM SALARIES;

SELECT EMPLOYEENAME, ROUND(SUM(TOTALPAY)) AS PAY FROM SALARIES
GROUP BY EMPLOYEENAME
ORDER BY PAY DESC
LIMIT 10;

SELECT EMPLOYEENAME, TOTALPAY FROM SALARIES
ORDER BY TOTALPAY DESC;

##### SHOW THE AVG OF BASEPAY, OVERTIMEPAY AND OTHERPAY FOR EACH EMP ###########

SELECT * FROM SALARIES;

SELECT EMPLOYEENAME AS EMP, AVG(BASEPAY) AS AVGBASE, AVG(OVERTIMEPAY) AS AVGOVER, AVG(OTHERPAY) AS AVGOTHER FROM SALARIES
GROUP BY EMPLOYEENAME;

###### SHOW ALL EMPLOYEES WHO HAVE THE ROLE MANAGER IN TH JOBTITLE ###########

SELECT * FROM SALARIES;

SELECT EMPLOYEENAME, JOBTITLE FROM SALARIES WHERE JOBTITLE REGEXP 'MANAGER' ;

###### SHOW ALL EMPLOYEES WHO HAVE JOB TITLE NOT EQUAL TO MANAER ###########

SELECT EMPLOYEENAME, JOBTITLE FROM SALARIES WHERE JOBTITLE != 'MANAGER%';

####### SHOW ALL EMP WITH TOTALPAY BETWEEN 50000 TO 75000 #####

SELECT * FROM SALARIES;

SELECT EMPLOYEENAME, TOTALPAY FROM SALARIES WHERE TOTALPAY BETWEEN  '50000' AND '75000'
ORDER BY TOTALPAY ASC;

###### SHOW ALL EMP WITH A BASEPAY LESS THAN 50,000 OR A TOTALPAY GREATER THAN 100000 ######

SELECT * FROM SALARIES;

SELECT EMPLOYEENAME,BASEPAY,TOTALPAY FROM SALARIES
WHERE BASEPAY < 50000 OR TOTALPAY > 100000;

### SHOW ALL EMP WITH TOTALPAY BETWEEN 125000 TO 150000 AND A JOBTITLE SHOULD BE DIRECTOR LEVEL ####

SELECT * FROM SALARIES;
SELECT EMPLOYEENAME,JOBTITLE, TOTALPAY FROM SALARIES WHERE JOBTITLE REGEXP 'DIRECTOR' AND TOTALPAY BETWEEN 125000 AND 150000;

###### SHOW ALL EMP ORDERED BY THEIR TOTALPAY IN DESC ORDER ######

SELECT EMPLOYEENAME,TOTALPAY FROM SALARIES
ORDER BY TOTALPAY DESC;
	
##### SHOW ALL JOBTITLE WITH AN AVG BASEPAY OF ATLEAST 100000 AND ORDER THEM BY THE AVG BASEPAY IN DESC ORDER ######

SELECT JOBTITLE, AVG(BASEPAY) AS AVGPAY FROM SALARIES
GROUP BY JOBTITLE
HAVING AVG(BASEPAY) >= 100000
ORDER BY AVGPAY DESC;

######### UPDATE THE BASEPAY OF ALL EMP WITH THE JOB TITLE CONTAINING MANAGER BY INCREASING IT BY 10% ######

SELECT * FROM SALARIES;

UPDATE SALARIES
SET BASEPAY = BASEPAY *1.1 
WHERE JOBTITLE REGEXP 'DIRECTOR';

##### DELETE ALL EMP WHO HAVE NO OVERTIMEPAY ###########

SELECT * FROM SALARIES;

DELETE FROM SALARIES
WHERE OVERTIMEPAY = 0;

SELECT COUNT(*) FROM SALARIES;
SELECT * FROM SALARIES;

############ DELETE THE COLUMN BENEFITS FROM TABLE BECAUSE ITS HAVE NULL VALUES ##########

ALTER TABLE SALARIES
DROP COLUMN BENEFITS;

SELECT * FROM SALARIES;



